server:
  port: 3000
application:
  domain: "msbpentest.pre"
  name: "MSB Pre Pentest 2017"
  logo: "JuiceShop_Logo.png"
  favicon: "favicon_v2.ico"
  numberOfRandomFakeUsers: 0
  showChallengeSolvedNotifications: true
  showCtfFlagsInNotifications: false
  showGitHubRibbon: true
  showChallengeHints: true
  theme: "slate" # Options: cerulean  cosmo  cyborg  darkly  flatly lumen  paper  readable  sandstone  simplex  slate  spacelab  superhero  united  yeti
  twitterUrl: "https://twitter.com/MSB"
  facebookUrl: "https://www.facebook.com/MSB"
  recyclePage:
    topProductImage: "fruit_press.jpg"
    bottomProductImage: "apple_pressings.jpg"
products:
  - name: "MSB"
    price: 1.99
    description: "Cong dong joy"
    image: "apple_juice.jpg"
    reviews:
      - text: 'I love MSB'
        author: 'admin' # Options: admin, jim, bender, ciso, support
  - name: "MSB"
    description: "Cong dong joy"
    price: 2.99
    image: 'orange_juice.jpg'
  - name: "MSB"
    description: "Cong dong joy"
    price: 8.99
    image: 'eggfruit_juice.jpg'
    reviews:
      - text: 'I love MSB'
        author: 'admin'
  - name: "MSB"
    description: "Cong dong joy"
    price: 4.99
    image: 'raspberry_juice.jpg'
  - name: "MSB"
    description: "Cong dong joy"
    price: 2.99
    image: 'lemon_juice.jpg'
  - name: "MSB"
    description: "Cong dong joy"
    price: 1.99
    image: 'banana_juice.jpg'
    reviews:
      - text: 'I love MSB'
        author: 'bender'
  - name: "MSB"
    description: "Cong dong joy"
    price: 22.49
    image: 'fan_shirt.jpg'
  - name: "MSB"
    description: "Cong dong joy"
    price: 22.49
    image: 'fan_girlie.jpg'
  - name: "MSB"
    description: "Cong dong joy"
    price: 0.01
    image: 'owasp_osaft.jpg'
    useForProductTamperingChallenge: true
  - name: "MSB"
    description: "Cong dong joy"
    price: 29.99
    image: 'undefined.jpg'
    useForChristmasSpecialChallenge: true
  - name: "MSB"
    description: "Cong dong joy"
    price: 999.99
    image: 'sticker.png'
    deletedDate: '2017-04-28'
  - name: "MSB"
    description: "Cong dong joy"
    price: 2.99
    image: 'sticker_facelift.png'
  - name: "MSB"
    description: "Cong dong joy"
    price: 2.99
    image: 'ctf_sticker.png'
  - name: "MSB"
    description: "Cong dong joy"
    price: 21.99
    image: 'fan_mug.jpg'
  - name: "MSB"
    description: "Cong dong joy"
    price: 49.99
    image: 'fan_hoodie.jpg'
  - name: "MSB"
    description: "Cong dong joy"
    price: 6.99
    image: 'woodruff_syrup.jpg'
  - name: "MSB"
    description: "Cong dong joy"
    price: 1.99
    image: 'green_smoothie.jpg'
    reviews:
      - text: 'I love MSB'
        author: 'jim'
  - name: "MSB"
    description: "Cong dong joy"
    price: 4.99
    image: 'quince.jpg'
  - name: "MSB"
    description: "Cong dong joy"
    price: 0.01
    image: 'owasplogo.png'
  - name: "MSB"
    description: "Cong dong joy"
    price: 0.89
    image: 'apple_pressings.jpg'
  - name: "MSB"
    description: "Cong dong joy"
    price: 89.99
    image: 'fruit_press.jpg'
  - name: "MSB"
    description: "Cong dong joy"
    price: 150
    image: 'white_raffards.jpg'
    reviews:
      - text: 'I love MSB'
        author: 'jim'
  - name: "MSB"
    description: "Cong dong joy"
    price: 99.99
    image: '3d_keychain.jpg' # Exif metadata contains "OpenSCAD" as subtle hint...
    fileForRetrieveBlueprintChallenge: 'JuiceShop.stl' # ...to blueprint file type
  - name: "MSB"
    description: "Cong dong joy"
    price: 278.74
    image: 'artwork.jpg'
  - name: "MSB"
    description: "Cong dong joy"
    price: 0.03
    image: 'waspy.png'
    deletedDate: '2017-07-01'
  - name: "MSB"
    description: "Cong dong joy"
    price: 1999
    image: 'melon_bike.jpeg'
  - name: "MSB"
    description: "Cong dong joy"
    price: 3.99
    image: 'strawberry_juice.jpeg'
  - name: "MSB"
    description: "Cong dong joy"
    price: 2.99
    image: 'carrot_juice.jpeg'
  - name: "MSB"
    description: "Cong dong joy"
    price: 20
    image: 'jawa_script.jpg'
  - name: "MSB"
    description: "Cong dong joy"
    price: 19.10
    image: 'stickersheet_se.png'

